import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./_components/Footer";
import NavBar from "./_components/NavBar";
import PasswordProtect from "./_components/PasswordProtect";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Still-Skilled",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        suppressHydrationWarning
      >
        <PasswordProtect>
          <NavBar/>
          <main className="p-5 mt-10 max-w-[1200px] mx-auto mb-20">
            {children}
            <SpeedInsights/>
            <Analytics/>
          </main>
          <Footer />
        </PasswordProtect>
      </body>
    </html>
  );
}
