import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./_components/Footer";
import NavBarContainer from "./_components/NavBarContainer";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        suppressHydrationWarning
      >
        <NavBarContainer />
        <main className="p-5 mt-10 max-w-[1200px] mx-auto mb-20">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
